# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

on:
    push:
        branches:
            - nzpmc-deploy

name: Cloud Run Build and Deploy
env:
    PROJECT_ID: ${{ secrets.GCP_PROJECT }}
    SERVICE: nzpmc-backend
    REGION: australia-southeast1

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: wdccprojects/nzpmc-backend:${{github.sha}}

            - name: Setup Cloud SDK
              uses: google-github-actions/setup-gcloud@v0.2.0
              with:
                  project_id: ${{ env.PROJECT_ID }}
                  service_account_key: ${{ secrets.GCP_SA_KEY }}
                  export_default_credentials: true # Set to true to authenticate the Cloud Run action

            - name: Deploy to Cloud Run
              id: deploy
              uses: google-github-actions/deploy-cloudrun@v0.4.0
              with:
                  service: ${{ env.SERVICE }}
                  image: docker.io/wdccprojects/nzpmc-backend:${{github.sha}}
                  region: ${{ env.REGION }}

            - name: Show Output
              run: echo ${{ steps.deploy.outputs.url }}
