name: Lint

on: [pull_request, push]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
           ref: ${{ github.ref }}
           fetch-depth: 0
           submodules: recursive 

      - name: Install Dependencies
        run: yarn

      - name: Run ESLint
        uses: sibiraj-s/action-eslint@v3
        with:
          all-files: true
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          annotations: true
