name: Lint

on: 
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'     # excludes main

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
           ref: ${{ github.ref }}
           fetch-depth: 0
           submodules: recursive 

      - name: Install Dependencies
        run: yarn

      - name: Run ESLint
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_extensions: js,ts,jsx,tsx
          prettier: true
          auto_fix: true
